### ISSUE TITLE
p-value

### ISSUE THREAD

**Issue by amirziai** [moajzashahab/Springboard#1]
Is this statement from [hospital EDA](https://github.com/moajzashahab/Springboard/blob/master/EDA%20miniprojects/Hospital%20Readmissions/sliderule_dsi_inferential_statistics_exercise_3.ipynb) true?
"The p-value we get is really small, 1.22E-25, which means even with α = .01 we can not reject the null hypothesis."

**Comment by moajzashahab** [comment]
Oh crap I meant we can
